#define EOF_Sym	0	/* EOF */
#define C_numberSym	1	/* number */
#define C_hexnumberSym	2	/* hexnumber */
#define C_stringD1Sym	3	/* string1 */
#define C_charSym	4	/* char */
#define C_regexD1Sym	5	/* regex1 */
#define C_ColonSym	6	/* Colon */
#define C_spaceD1Sym	7	/* space1 */
#define C_identifierSym	8	/* identifier */
#define C_DATASym	9	/* "DATA" */
#define C_VALUESym	10	/* "VALUE" */
#define C_PARAMETERSym	11	/* "PARAMETER" */
#define C_PARAMETERSSym	12	/* "PARAMETERS" */
#define C_TARGETSym	13	/* "TARGET" */
#define C_MESSAGESym	14	/* "MESSAGE" */
#define C_ENDSym	15	/* "END" */
#define C_CREATESym	16	/* "CREATE" */
#define C_KEYSym	17	/* "KEY" */
#define C_IDSym	18	/* "ID" */
#define C_DEFAULTSym	19	/* "DEFAULT" */
#define C_LENGTHSym	20	/* "LENGTH" */
#define C_DECIMALSSym	21	/* "DECIMALS" */
#define C_BOXEDSym	22	/* "BOXED" */
#define C_SUFFIXSym	23	/* "SUFFIX" */
#define C_COMPONENTSSym	24	/* "COMPONENTS" */
#define C_EXCEPTIONSSym	25	/* "EXCEPTIONS" */
#define C_KINDSym	26	/* "KIND" */
#define C_DELETESym	27	/* "DELETE" */
#define C_ACTIVATIONSym	28	/* "ACTIVATION" */
#define C_OFSym	29	/* "OF" */
#define C_EOFSym	30	/* "EOF" */
#define C_REPORTSym	31	/* "REPORT" */
#define C_NOSym	32	/* "NO" */
#define C_PAGESym	33	/* "PAGE" */
#define C_HEADINGSym	34	/* "HEADING" */
#define C_DEFININGSym	35	/* "DEFINING" */
#define C_DATABASESym	36	/* "DATABASE" */
#define C_REDUCEDSym	37	/* "REDUCED" */
#define C_FUNCTIONALITYSym	38	/* "FUNCTIONALITY" */
#define C_FUNCTIONSym	39	/* "FUNCTION" */
#define C_ENDFUNCTIONSym	40	/* "ENDFUNCTION" */
#define C_ENDSELECTSym	41	/* "ENDSELECT" */
#define C_FIELDSSym	42	/* "FIELDS" */
#define C_DISTINCTSym	43	/* "DISTINCT" */
#define C_FROMSym	44	/* "FROM" */
#define C_ASSym	45	/* "AS" */
#define C_USINGSym	46	/* "USING" */
#define C_CLIENTSym	47	/* "CLIENT" */
#define C_SPECIFIEDSym	48	/* "SPECIFIED" */
#define C_INNERSym	49	/* "INNER" */
#define C_LEFTSym	50	/* "LEFT" */
#define C_RIGHTSym	51	/* "RIGHT" */
#define C_OUTERSym	52	/* "OUTER" */
#define C_CROSSSym	53	/* "CROSS" */
#define C_JOINSym	54	/* "JOIN" */
#define C_ONSym	55	/* "ON" */
#define C_ORDERSym	56	/* "ORDER" */
#define C_BYSym	57	/* "BY" */
#define C_PRIMARYSym	58	/* "PRIMARY" */
#define C_ASCENDINGSym	59	/* "ASCENDING" */
#define C_DESCENDINGSym	60	/* "DESCENDING" */
#define C_APPENDINGSym	61	/* "APPENDING" */
#define C_CORRESPONDINGSym	62	/* "CORRESPONDING" */
#define C_PACKAGESym	63	/* "PACKAGE" */
#define C_SIZESym	64	/* "SIZE" */
#define C_SELECTSym	65	/* "SELECT" */
#define C_SINGLESym	66	/* "SINGLE" */
#define C_FORSym	67	/* "FOR" */
#define C_UPDATESym	68	/* "UPDATE" */
#define C_ENTRIESSym	69	/* "ENTRIES" */
#define C_INSym	70	/* "IN" */
#define C_WHERESym	71	/* "WHERE" */
#define C_GROUPSym	72	/* "GROUP" */
#define C_HAVINGSym	73	/* "HAVING" */
#define C_UNIONSym	74	/* "UNION" */
#define C_EXTENDEDSym	75	/* "EXTENDED" */
#define C_RESULTSym	76	/* "RESULT" */
#define C_CREATINGSym	77	/* "CREATING" */
#define C_READERSym	78	/* "READER" */
#define C_LOCATORSym	79	/* "LOCATOR" */
#define C_COLUMNSSym	80	/* "COLUMNS" */
#define C_BLOBSym	81	/* "BLOB" */
#define C_CLOBSym	82	/* "CLOB" */
#define C_OFFSETSym	83	/* "OFFSET" */
#define C_UPSym	84	/* "UP" */
#define C_TOSym	85	/* "TO" */
#define C_ROWSSym	86	/* "ROWS" */
#define C_BYPASSINGSym	87	/* "BYPASSING" */
#define C_BUFFERSym	88	/* "BUFFER" */
#define C_CONNECTIONSym	89	/* "CONNECTION" */
#define C_ENDWITHSym	90	/* "ENDWITH" */
#define C_TABLESSym	91	/* "TABLES" */
#define C_MOVESym	92	/* "MOVE" */
#define C_EXACTSym	93	/* "EXACT" */
#define C_PERCENTAGESym	94	/* "PERCENTAGE" */
#define C_EXPANDINGSym	95	/* "EXPANDING" */
#define C_NESTEDSym	96	/* "NESTED" */
#define C_KEEPINGSym	97	/* "KEEPING" */
#define C_APPENDSym	98	/* "APPEND" */
#define C_LINESym	99	/* "LINE" */
#define C_CASTINGSym	100	/* "CASTING" */
#define C_CONCATENATESym	101	/* "CONCATENATE" */
#define C_CHARACTERSym	102	/* "CHARACTER" */
#define C_BYTESym	103	/* "BYTE" */
#define C_MODESym	104	/* "MODE" */
#define C_SEPARATEDSym	105	/* "SEPARATED" */
#define C_RESPECTINGSym	106	/* "RESPECTING" */
#define C_BLANKSSym	107	/* "BLANKS" */
#define C_SEARCHSym	108	/* "SEARCH" */
#define C_STARTINGSym	109	/* "STARTING" */
#define C_ATSym	110	/* "AT" */
#define C_ENDINGSym	111	/* "ENDING" */
#define C_ABBREVIATEDSym	112	/* "ABBREVIATED" */
#define C_ANDSym	113	/* "AND" */
#define C_MARKSym	114	/* "MARK" */
#define C_RAISESym	115	/* "RAISE" */
#define C_EVENTSym	116	/* "EVENT" */
#define C_RESUMABLESym	117	/* "RESUMABLE" */
#define C_EXCEPTIONSym	118	/* "EXCEPTION" */
#define C_NUMBERSym	119	/* "NUMBER" */
#define C_DISPLAYSym	120	/* "DISPLAY" */
#define C_LIKESym	121	/* "LIKE" */
#define C_RAISINGSym	122	/* "RAISING" */
#define C_INDEXSym	123	/* "INDEX" */
#define C_TEXTSym	124	/* "TEXT" */
#define C_WITHOUTSym	125	/* "WITHOUT" */
#define C_MEMBERSSym	126	/* "MEMBERS" */
#define C_LOOPSym	127	/* "LOOP" */
#define C_VERSIONSym	128	/* "VERSION" */
#define C_SCREENSym	129	/* "SCREEN" */
#define C_ENDLOOPSym	130	/* "ENDLOOP" */
#define C_LOBSym	131	/* "LOB" */
#define C_HANDLESym	132	/* "HANDLE" */
#define C_EMPTYSym	133	/* "EMPTY" */
#define C_HEADERSym	134	/* "HEADER" */
#define C_UNIQUESym	135	/* "UNIQUE" */
#define C_PRIMARYUnderscoreKEYSym	136	/* "PRIMARY_KEY" */
#define C_ALIASSym	137	/* "ALIAS" */
#define C_STATICSSym	138	/* "STATICS" */
#define C_CONSTANTSSym	139	/* "CONSTANTS" */
#define C_BEGINSym	140	/* "BEGIN" */
#define C_COMMONSym	141	/* "COMMON" */
#define C_PARTSym	142	/* "PART" */
#define C_OCCURSSym	143	/* "OCCURS" */
#define C_VALIDSym	144	/* "VALID" */
#define C_BETWEENSym	145	/* "BETWEEN" */
#define C_ISSym	146	/* "IS" */
#define C_WRITESym	147	/* "WRITE" */
#define C_UNDERSym	148	/* "UNDER" */
#define C_CENTEREDSym	149	/* "CENTERED" */
#define C_EXPONENTSym	150	/* "EXPONENT" */
#define C_CURRENCYSym	151	/* "CURRENCY" */
#define C_ROUNDSym	152	/* "ROUND" */
#define C_UNITSym	153	/* "UNIT" */
#define C_ENVIRONMENTSym	154	/* "ENVIRONMENT" */
#define C_TIMESym	155	/* "TIME" */
#define C_FORMATSym	156	/* "FORMAT" */
#define C_ZONESym	157	/* "ZONE" */
#define C_STYLESym	158	/* "STYLE" */
#define C_MASKSym	159	/* "MASK" */
#define C_DDMMYYSym	160	/* "DDMMYY" */
#define C_MMDDYYSym	161	/* "MMDDYY" */
#define C_YYMMDDSym	162	/* "YYMMDD" */
#define C_CHECKBOXSym	163	/* "CHECKBOX" */
#define C_ICONSym	164	/* "ICON" */
#define C_SYMBOLSym	165	/* "SYMBOL" */
#define C_QUICKINFOSym	166	/* "QUICKINFO" */
#define C_CONTINUESym	167	/* "CONTINUE" */
#define C_CASESym	168	/* "CASE" */
#define C_WHENSym	169	/* "WHEN" */
#define C_ORSym	170	/* "OR" */
#define C_OTHERSSym	171	/* "OTHERS" */
#define C_ENDCASESym	172	/* "ENDCASE" */
#define C_FIELDSym	173	/* "FIELD" */
#define C_DUMMYSym	174	/* "DUMMY" */
#define C_OBJECTSym	175	/* "OBJECT" */
#define C_USERSym	176	/* "USER" */
#define C_DATASETSym	177	/* "DATASET" */
#define C_ADJACENTSym	178	/* "ADJACENT" */
#define C_DUPLICATESSym	179	/* "DUPLICATES" */
#define C_COMPARINGSym	180	/* "COMPARING" */
#define C_MEMORYSym	181	/* "MEMORY" */
#define C_SHAREDSym	182	/* "SHARED" */
#define C_VARYINGSym	183	/* "VARYING" */
#define C_NEXTSym	184	/* "NEXT" */
#define C_DOSym	185	/* "DO" */
#define C_TIMESSym	186	/* "TIMES" */
#define C_ENDDOSym	187	/* "ENDDO" */
#define C_OPTIONALSym	188	/* "OPTIONAL" */
#define C_EVENTSSym	189	/* "EVENTS" */
#define C_MODIFYSym	190	/* "MODIFY" */
#define C_CURRENTSym	191	/* "CURRENT" */
#define C_CHANGESym	192	/* "CHANGE" */
#define C_ENDONSym	193	/* "ENDON" */
#define C_OPENSym	194	/* "OPEN" */
#define C_CURSORSym	195	/* "CURSOR" */
#define C_HOLDSym	196	/* "HOLD" */
#define C_INPUTSym	197	/* "INPUT" */
#define C_OUTPUTSym	198	/* "OUTPUT" */
#define C_ENCODINGSym	199	/* "ENCODING" */
#define C_SKIPPINGSym	200	/* "SKIPPING" */
#define C_NATIVESym	201	/* "NATIVE" */
#define C_SMARTSym	202	/* "SMART" */
#define C_UNIXSym	203	/* "UNIX" */
#define C_WINDOWSSym	204	/* "WINDOWS" */
#define C_LINEFEEDSym	205	/* "LINEFEED" */
#define C_LEGACYSym	206	/* "LEGACY" */
#define C_BIGSym	207	/* "BIG" */
#define C_LITTLESym	208	/* "LITTLE" */
#define C_ENDIANSym	209	/* "ENDIAN" */
#define C_CODESym	210	/* "CODE" */
#define C_POSITIONSym	211	/* "POSITION" */
#define C_FILTERSym	212	/* "FILTER" */
#define C_IGNORINGSym	213	/* "IGNORING" */
#define C_CONVERSIONSym	214	/* "CONVERSION" */
#define C_ERRORSSym	215	/* "ERRORS" */
#define C_REPLACEMENTSym	216	/* "REPLACEMENT" */
#define C_FETCHSym	217	/* "FETCH" */
#define C_BOUNDSSym	218	/* "BOUNDS" */
#define C_PROVIDESym	219	/* "PROVIDE" */
#define C_INCLUDINGSym	220	/* "INCLUDING" */
#define C_GAPSSym	221	/* "GAPS" */
#define C_ENDPROVIDESym	222	/* "ENDPROVIDE" */
#define C_READSym	223	/* "READ" */
#define C_MAXIMUMSym	224	/* "MAXIMUM" */
#define C_ACTUALSym	225	/* "ACTUAL" */
#define C_WIDTHSym	226	/* "WIDTH" */
#define C_TEXTPOOLSym	227	/* "TEXTPOOL" */
#define C_LANGUAGESym	228	/* "LANGUAGE" */
#define C_SORTSym	229	/* "SORT" */
#define C_SUBMITSym	230	/* "SUBMIT" */
#define C_VIASym	231	/* "VIA" */
#define C_PROGRAMSym	232	/* "PROGRAM" */
#define C_EQSym	233	/* "EQ" */
#define C_NESym	234	/* "NE" */
#define C_CPSym	235	/* "CP" */
#define C_NPSym	236	/* "NP" */
#define C_GESym	237	/* "GE" */
#define C_LTSym	238	/* "LT" */
#define C_LESym	239	/* "LE" */
#define C_GTSym	240	/* "GT" */
#define C_NOTSym	241	/* "NOT" */
#define C_FREESym	242	/* "FREE" */
#define C_SELECTIONSSym	243	/* "SELECTIONS" */
#define C_LISTSym	244	/* "LIST" */
#define C_SPOOLSym	245	/* "SPOOL" */
#define C_ARCHIVESym	246	/* "ARCHIVE" */
#define C_DYNPROSym	247	/* "DYNPRO" */
#define C_JOBSym	248	/* "JOB" */
#define C_RETURNSym	249	/* "RETURN" */
#define C_TRYSym	250	/* "TRY" */
#define C_CATCHSym	251	/* "CATCH" */
#define C_BEFORESym	252	/* "BEFORE" */
#define C_UNWINDSym	253	/* "UNWIND" */
#define C_CLEANUPSym	254	/* "CLEANUP" */
#define C_ENDTRYSym	255	/* "ENDTRY" */
#define C_ASSOCIATIONSym	256	/* "ASSOCIATION" */
#define C_TYPESSym	257	/* "TYPES" */
#define C_ENUMSym	258	/* "ENUM" */
#define C_STRUCTURESym	259	/* "STRUCTURE" */
#define C_BASESym	260	/* "BASE" */
#define C_MESHSym	261	/* "MESH" */
#define C_SETSym	262	/* "SET" */
#define C_WHILESym	263	/* "WHILE" */
#define C_VARYSym	264	/* "VARY" */
#define C_ENDWHILESym	265	/* "ENDWHILE" */
#define C_TASKSym	266	/* "TASK" */
#define C_NEWSym	267	/* "NEW" */
#define C_BACKGROUNDSym	268	/* "BACKGROUND" */
#define C_SEPARATESym	269	/* "SEPARATE" */
#define C_DESTINATIONSym	270	/* "DESTINATION" */
#define C_CALLINGSym	271	/* "CALLING" */
#define C_PERFORMINGSym	272	/* "PERFORMING" */
#define C_IFSym	273	/* "IF" */
#define C_ELSEIFSym	274	/* "ELSEIF" */
#define C_ELSESym	275	/* "ELSE" */
#define C_ENDIFSym	276	/* "ENDIF" */
#define C_CLASSSym	277	/* "CLASS" */
#define C_DEFINITIONSym	278	/* "DEFINITION" */
#define C_DEFERREDSym	279	/* "DEFERRED" */
#define C_PUBLICSym	280	/* "PUBLIC" */
#define C_PROTECTEDSym	281	/* "PROTECTED" */
#define C_PRIVATESym	282	/* "PRIVATE" */
#define C_INHERITINGSym	283	/* "INHERITING" */
#define C_ABSTRACTSym	284	/* "ABSTRACT" */
#define C_FINALSym	285	/* "FINAL" */
#define C_ENABLEDSym	286	/* "ENABLED" */
#define C_TESTINGSym	287	/* "TESTING" */
#define C_RISKSym	288	/* "RISK" */
#define C_LEVELSym	289	/* "LEVEL" */
#define C_CRITICALSym	290	/* "CRITICAL" */
#define C_DANGEROUSSym	291	/* "DANGEROUS" */
#define C_HARMLESSSym	292	/* "HARMLESS" */
#define C_DURATIONSym	293	/* "DURATION" */
#define C_SHORTSym	294	/* "SHORT" */
#define C_MEDIUMSym	295	/* "MEDIUM" */
#define C_LONGSym	296	/* "LONG" */
#define C_GLOBALSym	297	/* "GLOBAL" */
#define C_FRIENDSSym	298	/* "FRIENDS" */
#define C_LOADSym	299	/* "LOAD" */
#define C_IMPLEMENTATIONSym	300	/* "IMPLEMENTATION" */
#define C_SECTIONSym	301	/* "SECTION" */
#define C_ENDCLASSSym	302	/* "ENDCLASS" */
#define C_METHODSym	303	/* "METHOD" */
#define C_ENDMETHODSym	304	/* "ENDMETHOD" */
#define C_ANYSym	305	/* "ANY" */
#define C_METHODSSym	306	/* "METHODS" */
#define C_REDEFINITIONSym	307	/* "REDEFINITION" */
#define C_IGNORESym	308	/* "IGNORE" */
#define C_FAILSym	309	/* "FAIL" */
#define C_PREFERREDSym	310	/* "PREFERRED" */
#define C_ADDSym	311	/* "ADD" */
#define C_THENSym	312	/* "THEN" */
#define C_UNTILSym	313	/* "UNTIL" */
#define C_GIVINGSym	314	/* "GIVING" */
#define C_ACCORDINGSym	315	/* "ACCORDING" */
#define C_ALIASESSym	316	/* "ALIASES" */
#define C_ASSERTSym	317	/* "ASSERT" */
#define C_SUBKEYSym	318	/* "SUBKEY" */
#define C_CONDITIONSym	319	/* "CONDITION" */
#define C_ASSIGNSym	320	/* "ASSIGN" */
#define C_COMPONENTSym	321	/* "COMPONENT" */
#define C_INCREMENTSym	322	/* "INCREMENT" */
#define C_FIRSTSym	323	/* "FIRST" */
#define C_LASTSym	324	/* "LAST" */
#define C_ENDATSym	325	/* "ENDAT" */
#define C_BACKSym	326	/* "BACK" */
#define C_CALLSym	327	/* "CALL" */
#define C_DIALOGSym	328	/* "DIALOG" */
#define C_SKIPSym	329	/* "SKIP" */
#define C_PROCEDURESym	330	/* "PROCEDURE" */
#define C_FLUSHSym	331	/* "FLUSH" */
#define C_TRANSACTIONSym	332	/* "TRANSACTION" */
#define C_OPTIONSSym	333	/* "OPTIONS" */
#define C_MESSAGESSym	334	/* "MESSAGES" */
#define C_TRANSFORMATIONSym	335	/* "TRANSFORMATION" */
#define C_OBJECTSSym	336	/* "OBJECTS" */
#define C_SOURCESym	337	/* "SOURCE" */
#define C_XMLSym	338	/* "XML" */
#define C_AREASym	339	/* "AREA" */
#define C_BADISym	340	/* "BADI" */
#define C_CLEARSym	341	/* "CLEAR" */
#define C_NULLSym	342	/* "NULL" */
#define C_CLOSESym	343	/* "CLOSE" */
#define C_COLLECTSym	344	/* "COLLECT" */
#define C_COMMITSym	345	/* "COMMIT" */
#define C_WORKSym	346	/* "WORK" */
#define C_WAITSym	347	/* "WAIT" */
#define C_COMPUTESym	348	/* "COMPUTE" */
#define C_CONDENSESym	349	/* "CONDENSE" */
#define C_CONTROLSSym	350	/* "CONTROLS" */
#define C_TABLEVIEWSym	351	/* "TABLEVIEW" */
#define C_TABSTRIPSym	352	/* "TABSTRIP" */
#define C_CONVERTSym	353	/* "CONVERT" */
#define C_SORTABLESym	354	/* "SORTABLE" */
#define C_STAMPSym	355	/* "STAMP" */
#define C_DAYLIGHTSym	356	/* "DAYLIGHT" */
#define C_SAVINGSym	357	/* "SAVING" */
#define C_DEMANDSym	358	/* "DEMAND" */
#define C_CONTEXTSym	359	/* "CONTEXT" */
#define C_DESCRIBESym	360	/* "DESCRIBE" */
#define C_DISTANCESym	361	/* "DISTANCE" */
#define C_PAGESSym	362	/* "PAGES" */
#define C_DETAILSym	363	/* "DETAIL" */
#define C_DIVIDESym	364	/* "DIVIDE" */
#define C_TITLESym	365	/* "TITLE" */
#define C_BACKUPSym	366	/* "BACKUP" */
#define C_EXITSym	367	/* "EXIT" */
#define C_SQLSym	368	/* "SQL" */
#define C_EXPORTSym	369	/* "EXPORT" */
#define C_INTERNALSym	370	/* "INTERNAL" */
#define C_COMPRESSIONSym	371	/* "COMPRESSION" */
#define C_OFFSym	372	/* "OFF" */
#define C_EXTRACTSym	373	/* "EXTRACT" */
#define C_FINDSym	374	/* "FIND" */
#define C_OCCURRENCESym	375	/* "OCCURRENCE" */
#define C_OCCURRENCESSym	376	/* "OCCURRENCES" */
#define C_SUBSTRINGSym	377	/* "SUBSTRING" */
#define C_REGEXSym	378	/* "REGEX" */
#define C_MATCHSym	379	/* "MATCH" */
#define C_COUNTSym	380	/* "COUNT" */
#define C_RESULTSSym	381	/* "RESULTS" */
#define C_SUBMATCHESSym	382	/* "SUBMATCHES" */
#define C_COLORSym	383	/* "COLOR" */
#define C_COLUnderscoreBACKGROUNDSym	384	/* "COL_BACKGROUND" */
#define C_COLUnderscoreHEADINGSym	385	/* "COL_HEADING" */
#define C_COLUnderscoreNORMALSym	386	/* "COL_NORMAL" */
#define C_COLUnderscoreTOTALSym	387	/* "COL_TOTAL" */
#define C_COLUnderscoreKEYSym	388	/* "COL_KEY" */
#define C_COLUnderscorePOSITIVESym	389	/* "COL_POSITIVE" */
#define C_COLUnderscoreNEGATIVESym	390	/* "COL_NEGATIVE" */
#define C_COLUnderscoreGROUPSym	391	/* "COL_GROUP" */
#define C_INTENSIFIEDSym	392	/* "INTENSIFIED" */
#define C_INVERSESym	393	/* "INVERSE" */
#define C_HOTSPOTSym	394	/* "HOTSPOT" */
#define C_FRAMESSym	395	/* "FRAMES" */
#define C_RESETSym	396	/* "RESET" */
#define C_GENERATESym	397	/* "GENERATE" */
#define C_SUBROUTINESym	398	/* "SUBROUTINE" */
#define C_POOLSym	399	/* "POOL" */
#define C_INCLUDESym	400	/* "INCLUDE" */
#define C_GETSym	401	/* "GET" */
#define C_FILTERSSym	402	/* "FILTERS" */
#define C_BITSym	403	/* "BIT" */
#define C_ATTRIBUTESSym	404	/* "ATTRIBUTES" */
#define C_LOCALESym	405	/* "LOCALE" */
#define C_COUNTRYSym	406	/* "COUNTRY" */
#define C_MODIFIERSym	407	/* "MODIFIER" */
#define C_EXCLUDINGSym	408	/* "EXCLUDING" */
#define C_PROPERTYSym	409	/* "PROPERTY" */
#define C_RUNSym	410	/* "RUN" */
#define C_HIDESym	411	/* "HIDE" */
#define C_IMPORTSym	412	/* "IMPORT" */
#define C_ACCEPTINGSym	413	/* "ACCEPTING" */
#define C_PADDINGSym	414	/* "PADDING" */
#define C_TRUNCATIONSym	415	/* "TRUNCATION" */
#define C_BOUNDARIESSym	416	/* "BOUNDARIES" */
#define C_DIRECTORYSym	417	/* "DIRECTORY" */
#define C_RENAMINGSym	418	/* "RENAMING" */
#define C_FOUNDSym	419	/* "FOUND" */
#define C_INFOTYPESSym	420	/* "INFOTYPES" */
#define C_PERSONSym	421	/* "PERSON" */
#define C_INITIALIZATIONSym	422	/* "INITIALIZATION" */
#define C_INSERTSym	423	/* "INSERT" */
#define C_VALUESSym	424	/* "VALUES" */
#define C_DUPLICATESym	425	/* "DUPLICATE" */
#define C_KEYSSym	426	/* "KEYS" */
#define C_ENTRYSym	427	/* "ENTRY" */
#define C_ARITHMETICSym	428	/* "ARITHMETIC" */
#define C_UNICODESym	429	/* "UNICODE" */
#define C_ENABLINGSym	430	/* "ENABLING" */
#define C_INTERFACESym	431	/* "INTERFACE" */
#define C_ENDINTERFACESym	432	/* "ENDINTERFACE" */
#define C_INTERFACESSym	433	/* "INTERFACES" */
#define C_PARTIALLYSym	434	/* "PARTIALLY" */
#define C_IMPLEMENTEDSym	435	/* "IMPLEMENTED" */
#define C_LEAVESym	436	/* "LEAVE" */
#define C_LOCALSym	437	/* "LOCAL" */
#define C_MINIMUMSym	438	/* "MINIMUM" */
#define C_MODULESym	439	/* "MODULE" */
#define C_ENDMODULESym	440	/* "ENDMODULE" */
#define C_MULTIPLYSym	441	/* "MULTIPLY" */
#define C_SCROLLINGSym	442	/* "SCROLLING" */
#define C_PRINTSym	443	/* "PRINT" */
#define C_NODESSym	444	/* "NODES" */
#define C_OVERLAYSym	445	/* "OVERLAY" */
#define C_ONLYSym	446	/* "ONLY" */
#define C_PACKSym	447	/* "PACK" */
#define C_OBLIGATORYSym	448	/* "OBLIGATORY" */
#define C_VISIBLESym	449	/* "VISIBLE" */
#define C_LISTBOXSym	450	/* "LISTBOX" */
#define C_RADIOBUTTONSym	451	/* "RADIOBUTTON" */
#define C_MODIFSym	452	/* "MODIF" */
#define C_LOWERSym	453	/* "LOWER" */
#define C_MATCHCODESym	454	/* "MATCHCODE" */
#define C_PATTERNSym	455	/* "PATTERN" */
#define C_PERFORMSym	456	/* "PERFORM" */
#define C_ROLLBACKSym	457	/* "ROLLBACK" */
#define C_RANGESSym	458	/* "RANGES" */
#define C_RECEIVESym	459	/* "RECEIVE" */
#define C_REFRESHSym	460	/* "REFRESH" */
#define C_CONTROLSym	461	/* "CONTROL" */
#define C_REJECTSym	462	/* "REJECT" */
#define C_REPLACESym	463	/* "REPLACE" */
#define C_RESERVESym	464	/* "RESERVE" */
#define C_RESUMESym	465	/* "RESUME" */
#define C_RETRYSym	466	/* "RETRY" */
#define C_SCROLLSym	467	/* "SCROLL" */
#define C_COLUMNSym	468	/* "COLUMN" */
#define C_PLACESSym	469	/* "PLACES" */
#define C_FORWARDSym	470	/* "FORWARD" */
#define C_BACKWARDSym	471	/* "BACKWARD" */
#define C_INTERVALSSym	472	/* "INTERVALS" */
#define C_OPTIONSym	473	/* "OPTION" */
#define C_SELECTIONSym	474	/* "SELECTION" */
#define C_LOWSym	475	/* "LOW" */
#define C_HIGHSym	476	/* "HIGH" */
#define C_TABSym	477	/* "TAB" */
#define C_BLANKSym	478	/* "BLANK" */
#define C_FILESym	479	/* "FILE" */
#define C_HANDLERSym	480	/* "HANDLER" */
#define C_INSTANCESSym	481	/* "INSTANCES" */
#define C_MARGINSym	482	/* "MARGIN" */
#define C_IMMEDIATELYSym	483	/* "IMMEDIATELY" */
#define C_ANALYZERSym	484	/* "ANALYZER" */
#define C_CLOCKSym	485	/* "CLOCK" */
#define C_RESOLUTIONSym	486	/* "RESOLUTION" */
#define C_TITLEBARSym	487	/* "TITLEBAR" */
#define C_SHIFTSym	488	/* "SHIFT" */
#define C_CIRCULARSym	489	/* "CIRCULAR" */
#define C_DELETINGSym	490	/* "DELETING" */
#define C_LEADINGSym	491	/* "LEADING" */
#define C_TRAILINGSym	492	/* "TRAILING" */
#define C_STOPSym	493	/* "STOP" */
#define C_SUBTRACTSym	494	/* "SUBTRACT" */
#define C_SUMSym	495	/* "SUM" */
#define C_SUMMARYSym	496	/* "SUMMARY" */
#define C_SUMMINGSym	497	/* "SUMMING" */
#define C_SUPPLYSym	498	/* "SUPPLY" */
#define C_SUPPRESSSym	499	/* "SUPPRESS" */
#define C_SWITCHSTATESSym	500	/* "SWITCHSTATES" */
#define C_DURINGSym	501	/* "DURING" */
#define C_TRANSFERSym	502	/* "TRANSFER" */
#define C_TRANSLATESym	503	/* "TRANSLATE" */
#define C_UPPERSym	504	/* "UPPER" */
#define C_TRUNCATESym	505	/* "TRUNCATE" */
#define C_ULINESym	506	/* "ULINE" */
#define C_UNASSIGNSym	507	/* "UNASSIGN" */
#define C_UNPACKSym	508	/* "UNPACK" */
#define C_SECONDSSym	509	/* "SECONDS" */
#define C_ASYNCHRONOUSSym	510	/* "ASYNCHRONOUS" */
#define C_TASKSSym	511	/* "TASKS" */
#define C_MESSAGINGSym	512	/* "MESSAGING" */
#define C_CHANNELSSym	513	/* "CHANNELS" */
#define C_PUSHSym	514	/* "PUSH" */
#define C_WINDOWSym	515	/* "WINDOW" */
#define C_SPLITSym	516	/* "SPLIT" */
#define C_DIVSym	517	/* "DIV" */
#define C_MODSym	518	/* "MOD" */
#define C_EQUIVSym	519	/* "EQUIV" */
#define C_COSym	520	/* "CO" */
#define C_CNSym	521	/* "CN" */
#define C_CASym	522	/* "CA" */
#define C_NASym	523	/* "NA" */
#define C_CSSym	524	/* "CS" */
#define C_NSSym	525	/* "NS" */
#define C_INSTANCESym	526	/* "INSTANCE" */
#define C_BOUNDSym	527	/* "BOUND" */
#define C_ASSIGNEDSym	528	/* "ASSIGNED" */
#define C_SUPPLIEDSym	529	/* "SUPPLIED" */
#define C_REQUESTEDSym	530	/* "REQUESTED" */
#define C_REFSym	531	/* "REF" */
#define C_SORTEDSym	532	/* "SORTED" */
#define C_EDITSym	533	/* "EDIT" */
#define C_NODESym	534	/* "NODE" */
#define C_ALLSym	535	/* "ALL" */
#define C_OTHERSym	536	/* "OTHER" */
#define C_INITIALSym	537	/* "INITIAL" */
#define C_ASSIGNINGSym	538	/* "ASSIGNING" */
#define C_REFERENCESym	539	/* "REFERENCE" */
#define C_EXPORTINGSym	540	/* "EXPORTING" */
#define C_TRANSPORTINGSym	541	/* "TRANSPORTING" */
#define C_HASHEDSym	542	/* "HASHED" */
#define C_RANGESym	543	/* "RANGE" */
#define C_BINARYSym	544	/* "BINARY" */
#define C_IMPORTINGSym	545	/* "IMPORTING" */
#define C_RETURNINGSym	546	/* "RETURNING" */
#define C_LINESSym	547	/* "LINES" */
#define C_STANDARDSym	548	/* "STANDARD" */
#define C_CHECKSym	549	/* "CHECK" */
#define C_TYPESym	550	/* "TYPE" */
#define C_LparenSym	551	/* "(" */
#define C_RparenSym	552	/* ")" */
#define C_EqualGreaterSym	553	/* "=>" */
#define C_TYPEMinusPOOLSym	554	/* "TYPE-POOL" */
#define C_PointSym	555	/* "." */
#define C_LINEMinusSIZESym	556	/* "LINE-SIZE" */
#define C_LINEMinusCOUNTSym	557	/* "LINE-COUNT" */
#define C_MESSAGEMinusIDSym	558	/* "MESSAGE-ID" */
#define C_StarSym	559	/* "*" */
#define C_CommaSym	560	/* "," */
#define C_TildeSym	561	/* "~" */
#define C_TildeStarSym	562	/* "~*" */
#define C_aggregateSym	563	/* "aggregate" */
#define C_INTOSym	564	/* "INTO" */
#define C_TABLESym	565	/* "TABLE" */
#define C_AtDATASym	566	/* "@DATA" */
#define C_AtSym	567	/* "@" */
#define C_PlusSym	568	/* "+" */
#define C_WITHSym	569	/* "WITH" */
#define C_QueryTOSym	570	/* "?TO" */
#define C_MOVEMinusCORRESPONDINGSym	571	/* "MOVE-CORRESPONDING" */
#define C_LbrackSym	572	/* "[" */
#define C_RbrackSym	573	/* "]" */
#define C_EqualSym	574	/* "=" */
#define C_NONMinusUNIQUESym	575	/* "NON-UNIQUE" */
#define C_CLASSMinusDATASym	576	/* "CLASS-DATA" */
#define C_READMinusONLYSym	577	/* "READ-ONLY" */
#define C_SlashSym	578	/* "/" */
#define C_StarStarSym	579	/* "**" */
#define C_NOMinusGAPSym	580	/* "NO-GAP" */
#define C_LEFTMinusJUSTIFIEDSym	581	/* "LEFT-JUSTIFIED" */
#define C_RIGHTMinusJUSTIFIEDSym	582	/* "RIGHT-JUSTIFIED" */
#define C_NOMinusGROUPINGSym	583	/* "NO-GROUPING" */
#define C_NOMinusSIGNSym	584	/* "NO-SIGN" */
#define C_NOMinusZEROSym	585	/* "NO-ZERO" */
#define C_DDSlashMMSlashYYSym	586	/* "DD/MM/YY" */
#define C_MMSlashDDSlashYYSym	587	/* "MM/DD/YY" */
#define C_DDSlashMMSlashYYYYSym	588	/* "DD/MM/YYYY" */
#define C_MMSlashDDSlashYYYYSym	589	/* "MM/DD/YYYY" */
#define C_AUTHORITYMinusCHECKSym	590	/* "AUTHORITY-CHECK" */
#define C_BYTEMinusORDERSym	591	/* "BYTE-ORDER" */
#define C_NONMinusUNICODESym	592	/* "NON-UNICODE" */
#define C_STABLESym	593	/* "STABLE" */
#define C_SELECTIONMinusSCREENSym	594	/* "SELECTION-SCREEN" */
#define C_SELECTIONMinusSETSym	595	/* "SELECTION-SET" */
#define C_SELECTIONMinusSETSSym	596	/* "SELECTION-SETS" */
#define C_SELECTIONMinusTABLESym	597	/* "SELECTION-TABLE" */
#define C_SAPMinusSPOOLSym	598	/* "SAP-SPOOL" */
#define C_forSym	599	/* "for" */
#define C_SemicolonSym	600	/* ";" */
#define C_CHANGINGSym	601	/* "CHANGING" */
#define C_errorUnderscoremessageSym	602	/* "error_message" */
#define C_systemUnderscorefailureSym	603	/* "system_failure" */
#define C_communicationUnderscorefaiSym	604	/* "communication_failure" */
#define C_resourceUnderscorefailureSym	605	/* "resource_failure" */
#define C_PARAMETERMinusTABLESym	606	/* "PARAMETER-TABLE" */
#define C_EXCEPTIONMinusTABLESym	607	/* "EXCEPTION-TABLE" */
#define C_returnSym	608	/* "return" */
#define C_CLASSMinusMETHODSSym	609	/* "CLASS-METHODS" */
#define C_ADDMinusCORRESPONDINGSym	610	/* "ADD-CORRESPONDING" */
#define C_MinusGreaterSym	611	/* "->" */
#define C_BREAKMinusPOINTSym	612	/* "BREAK-POINT" */
#define C_CUSTOMERMinusFUNCTIONSym	613	/* "CUSTOMER-FUNCTION" */
#define C_RECEIVINGSym	614	/* "RECEIVING" */
#define C_QUEUEMinusONLYSym	615	/* "QUEUE-ONLY" */
#define C_CLASSMinusEVENTSSym	616	/* "CLASS-EVENTS" */
#define C_CLASSMinusPOOLSym	617	/* "CLASS-POOL" */
#define C_QuerySym	618	/* "?" */
#define C_NOMinusGAPSSym	619	/* "NO-GAPS" */
#define C_OUTPUTMinusLENGTHSym	620	/* "OUTPUT-LENGTH" */
#define C_HELPMinusIDSym	621	/* "HELP-ID" */
#define C_FIRSTMinusLINESym	622	/* "FIRST-LINE" */
#define C_TOPMinusLINESSym	623	/* "TOP-LINES" */
#define C_TITLEMinusLINESSym	624	/* "TITLE-LINES" */
#define C_HEADMinusLINESSym	625	/* "HEAD-LINES" */
#define C_ENDMinusLINESSym	626	/* "END-LINES" */
#define C_DIVIDEMinusCORRESPONDINGSym	627	/* "DIVIDE-CORRESPONDING" */
#define C_EDITORMinusCALLSym	628	/* "EDITOR-CALL" */
#define C_DISPLAYMinusMODESym	629	/* "DISPLAY-MODE" */
#define C_ENDMinusOFMinusPAGESym	630	/* "END-OF-PAGE" */
#define C_ENDMinusOFMinusSELECTIONSym	631	/* "END-OF-SELECTION" */
#define C_STEPMinusLOOPSym	632	/* "STEP-LOOP" */
#define C_FIELDMinusGROUPSSym	633	/* "FIELD-GROUPS" */
#define C_FIELDMinusSYMBOLSSym	634	/* "FIELD-SYMBOLS" */
#define C_FUNCTIONMinusPOOLSym	635	/* "FUNCTION-POOL" */
#define C_SHORTDUMPMinusIDSym	636	/* "SHORTDUMP-ID" */
#define C_FILTERMinusTABLESym	637	/* "FILTER-TABLE" */
#define C_PFMinusSTATUSSym	638	/* "PF-STATUS" */
#define C_MAJORMinusIDSym	639	/* "MAJOR-ID" */
#define C_MINORMinusIDSym	640	/* "MINOR-ID" */
#define C_CHARMinusTOMinusHEXSym	641	/* "CHAR-TO-HEX" */
#define C_FIXEDMinusPOINTSym	642	/* "FIXED-POINT" */
#define C_INTERFACEMinusPOOLSym	643	/* "INTERFACE-POOL" */
#define C_LISTMinusPROCESSINGSym	644	/* "LIST-PROCESSING" */
#define C_LOADMinusOFMinusPROGRAMSym	645	/* "LOAD-OF-PROGRAM" */
#define C_LOGMinusPOINTSym	646	/* "LOG-POINT" */
#define C_MULTIPLYMinusCORRESPONDINGSym	647	/* "MULTIPLY-CORRESPONDING" */
#define C_NEWMinusLINESym	648	/* "NEW-LINE" */
#define C_NOMinusSCROLLINGSym	649	/* "NO-SCROLLING" */
#define C_NEWMinusPAGESym	650	/* "NEW-PAGE" */
#define C_WITHMinusTITLESym	651	/* "WITH-TITLE" */
#define C_NOMinusTITLESym	652	/* "NO-TITLE" */
#define C_WITHMinusHEADINGSym	653	/* "WITH-HEADING" */
#define C_NOMinusHEADINGSym	654	/* "NO-HEADING" */
#define C_NOMinusTOPOFPAGESym	655	/* "NO-TOPOFPAGE" */
#define C_NEWMinusSECTIONSym	656	/* "NEW-SECTION" */
#define C_NOMinusDISPLAYSym	657	/* "NO-DISPLAY" */
#define C_USERMinusCOMMANDSym	658	/* "USER-COMMAND" */
#define C_HELPMinusREQUESTSym	659	/* "HELP-REQUEST" */
#define C_VALUEMinusREQUESTSym	660	/* "VALUE-REQUEST" */
#define C_PRINTMinusCONTROLSym	661	/* "PRINT-CONTROL" */
#define C_INDEXMinusLINESym	662	/* "INDEX-LINE" */
#define C_SELECTMinusOPTIONSSym	663	/* "SELECT-OPTIONS" */
#define C_NOMinusEXTENSIONSym	664	/* "NO-EXTENSION" */
#define C_SCROLLMinusBOUNDARYSym	665	/* "SCROLL-BOUNDARY" */
#define C_SUBTRACTMinusCORRESPONDINGSym	666	/* "SUBTRACT-CORRESPONDING" */
#define C_SYNTAXMinusCHECKSym	667	/* "SYNTAX-CHECK" */
#define C_TESTMinusINJECTIONSym	668	/* "TEST-INJECTION" */
#define C_ENDMinusTESTMinusINJECTIONSym	669	/* "END-TEST-INJECTION" */
#define C_TESTMinusSEAMSym	670	/* "TEST-SEAM" */
#define C_ENDMinusTESTMinusSEAMSym	671	/* "END-TEST-SEAM" */
#define C_TOPMinusOFMinusPAGESym	672	/* "TOP-OF-PAGE" */
#define C_LINEMinusSELECTIONSym	673	/* "LINE-SELECTION" */
#define C_TYPEMinusPOOLSSym	674	/* "TYPE-POOLS" */
#define C_BarBarSym	675	/* "||" */
#define C_AndAndSym	676	/* "&&" */
#define C_BarSym	677	/* "|" */
#define C_UparrowSym	678	/* "^" */
#define C_AndSym	679	/* "&" */
#define C_LessGreaterSym	680	/* "<>" */
#define C_LessSym	681	/* "<" */
#define C_GreaterSym	682	/* ">" */
#define C_LessEqualSym	683	/* "<=" */
#define C_GreaterEqualSym	684	/* ">=" */
#define C_BYTEMinusCOSym	685	/* "BYTE-CO" */
#define C_BYTEMinusCNSym	686	/* "BYTE-CN" */
#define C_BYTEMinusCASym	687	/* "BYTE-CA" */
#define C_BYTEMinusNASym	688	/* "BYTE-NA" */
#define C_BYTEMinusCSSym	689	/* "BYTE-CS" */
#define C_BYTEMinusNSSym	690	/* "BYTE-NS" */
#define C_LessLessSym	691	/* "<<" */
#define C_GreaterGreaterSym	692	/* ">>" */
#define C_MinusSym	693	/* "-" */
#define C_PercentSym	694	/* "%" */
#define C_HashSym	695	/* "#" */
#define C_StarEqualSym	696	/* "*=" */
#define C_SlashEqualSym	697	/* "/=" */
#define C_PercentEqualSym	698	/* "%=" */
#define C_PlusEqualSym	699	/* "+=" */
#define C_MinusEqualSym	700	/* "-=" */
#define C_AndEqualSym	701	/* "&=" */
#define C_UparrowEqualSym	702	/* "^=" */
#define C_LessLessEqualSym	703	/* "<<=" */
#define C_GreaterGreaterEqualSym	704	/* ">>=" */
#define C_QueryEqualSym	705	/* "?=" */
#define C_BangSym	706	/* "!" */
#define No_Sym	707	/* not */
#define C_PreProcessorSym	708	/* PreProcessor */
#define MAXT	No_Sym	/* Max Terminals */
